source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.3"

target 'imitationOfBSBDJ' do

    pod "SDWebImage"
    pod "AFNetworking"
    pod "SVProgressHUD"
    pod "MJExtension"
    pod "MJRefresh"
    pod "DACircularProgress"
    pod "pop"
    pod "DOUAudioStreamer"

end


